### ISSUE TITLE
No such file or directory  driver/dac_continuous.h: 

### ISSUE THREAD

**Issue by NW-Lab** [Moddable-OpenSource/moddable#1275] opened 2023-12-21 07:04 UTC
Hello,

When building with the Windows Node-RED MCU Plugin, an error occurs during the build.
````
c:\pjt\moddable\modules\pins\i2s\audioout.c:75:26: fatal error: driver/dac_continuous.h: No such file or directory
    75 | #include "driver/dac_continuous.h"
       | ^~~~~~~~~~~~~~~~~~~~~~~~~
````

The version is as below
```
21 Dec 15:47:28 - [info]

Welcome to Node-RED
===================

21 Dec 15:47:28 - [info] Node-RED version: v3.1.0
21 Dec 15:47:28 - [info] Node.js  version: v18.13.0
21 Dec 15:47:28 - [info] Windows_NT 10.0.22631 x64 LE
21 Dec 15:47:29 - [info] Loading palette nodes
21 Dec 15:47:29 - [info] Node-RED MCU Edition Runtime Version: #548dc37
21 Dec 15:47:29 - [info] Node-RED MCU Edition Plugin  Version: v1.3.2
21 Dec 15:47:30 - [info] Moddable SDK Version: v4.3.4-19-g0bd542e (x86)
21 Dec 15:47:30 - [info] *** node-red-mcu-plugin:
21 Dec 15:47:30 - [info] It looks as if a new platform option has been added.
```
Platform is esp32/m5stack

Flow is Inject(Timestamp) and Debug Node.
![image](https://github.com/Moddable-OpenSource/moddable/assets/8869009/66bed6ec-447f-421e-ba90-7c0ca8e64fd4)

Thanks,

**Comment by mkellner** [comment] 2023-12-21 08:47
Can you try to add `-I$(IDF_PATH)\components\driver\dac\include` to the tools/mcconfig/nmake.esp32.mk file?

```
diff --git a/tools/mcconfig/nmake.esp32.mk b/tools/mcconfig/nmake.esp32.mk
index 37c2dfc89..4b17fe352 100644
--- a/tools/mcconfig/nmake.esp32.mk
+++ b/tools/mcconfig/nmake.esp32.mk
@@ -193,6 +193,7 @@ INC_DIRS = \
        -I$(IDF_PATH)\components\bt\include\$(ESP32_BT_SUBCLASS)\include \
        -I$(IDF_PATH)\components\bt\host\bluedroid\api\include \
        -I$(IDF_PATH)\components\bt\host\bluedroid\api\include\api \
+    -I$(IDF_PATH)\components\driver\dac\include \
        -I$(IDF_PATH)\components\driver\gpio\include \
        -I$(IDF_PATH)\components\driver\gptimer\include \
        -I$(IDF_PATH)\components\driver\i2c\include \
```

**Comment by NW-Lab** [comment] 2023-12-21 09:02
mkellner san

Thank you for your prompt response.
The problem has been resolved.

Thank you.

**Comment by NW-Lab** [comment] 2024-01-04 02:17
mkellner san

hello
Not reflected in new releases.

thanks,

**Comment by mkellner** [comment] 2024-01-04 03:43
My apologies.

**Comment by phoddie** [comment] 2024-01-10 00:18
The commit is live now. Closing. If the problem is still present, please re-open with details. Thank you.

**Closed as completed by phoddie** 2024-01-10 00:18 UTC
