### ISSUE TITLE
Error when compiling QR code example on mac - file missing 

### ISSUE THREAD

**Issue by kairos0ne** [Moddable-OpenSource/moddable#1216] opened 2023-09-22 23:06 UTC
**Build environment:** macOS
**Moddable SDK version:** 4.1-32-gc5845e51c
**Target device:** mac

**Description**
<img width="1002" alt="image" src="https://github.com/Moddable-OpenSource/moddable/assets/15980261/240e238e-02dd-4ec0-affe-2a8f198f6b5d">

**Comment by phoddie** [comment] 2023-09-23 02:41
Thanks for the report. I'm able to reproduce the error. It looks like fallout from the recent set of manifest improvements. I'll post a fix in the next day or so.

**Comment by phoddie** [comment] 2023-09-23 16:22
The application manifest at `$MODDABLE/examples/data/qrcode/manifest.json` should also include `$(MODDABLE)/examples/manifest_commodetto.json`.With that in place, it builds and runs as expected. I'll commit that and it should be available in this repo in the coming days.

FWIW – `manifest_commodetto.json` is a required include for projects using Commodetto and Poco directly. For projects using Piu (which uses Commodetto and Poco), it is not necessary to include `manifest_commodetto.json` as the necessary pieces are included by `manifest_piu,json`, which is required for projects using Piu.

**Comment by phoddie** [comment] 2023-09-29 20:56
Fix committed. Closing.

**Closed as completed by phoddie** 2023-09-29 20:56 UTC
