### ISSUE TITLE
[ESP-IDF 5] out of memory error in fetch example

### ISSUE THREAD

**Issue by stc1988** [Moddable-OpenSource/moddable#1090] opened 2023-04-14 14:09 UTC
**Moddable:**  **Moddable:**  b042dc8723af4dbdd66d840be632812256bf6e99
**Build environment:** macOS,
**Target device:** eps32/m5stack_core2

**Steps to Reproduce**
Build `examples/io/tcp/fetch` with `mcconfig -d -m -p esp32/m5stack_core2 ssid="wifi_ssid" password="wifi_passwod"`

xsbug has no response.

**Other information**

`mcconfig -i -m -p esp32/m5stack_core2 ssid="wifi_ssid" password="wifi_passwod"` shows below log continuously.

```
I (14) cpu_start: Pro cpu up.
I (14) cpu_start: Starting app cpu, entry point is 0x40080e54
0x40080e54: call_start_cpu1 at /Users/satoshi/.local/share/esp32/esp-idf/components/esp_system/port/cpu_start.c:142

I (0) cpu_start: App cpu up.
I (25) cpu_start: Pro cpu start user code
I (25) cpu_start: cpu freq: 240000000 Hz
I (25) cpu_start: Application information:
I (27) cpu_start: Project name:     xs_esp32
I (31) cpu_start: App version:      3.8.0-67-g936dd943
I (36) cpu_start: Compile time:     Apr 14 2023 22:55:20
I (41) cpu_start: ELF file SHA256:  70d611be03a7961b...
I (46) cpu_start: ESP-IDF:          v5.0
I (50) heap_init: Initializing. RAM available for dynamic allocation:
I (56) heap_init: At 3FFAE6E0 len 00001920 (6 KiB): DRAM
I (61) heap_init: At 3FFB8750 len 000278B0 (158 KiB): DRAM
I (66) heap_init: At 3FFE0440 len 00003AE0 (14 KiB): D/IRAM
I (71) heap_init: At 3FFE4350 len 0001BCB0 (111 KiB): D/IRAM
I (77) heap_init: At 4009139C len 0000EC64 (59 KiB): IRAM
I (82) spi_flash: detected chip: generic
I (86) spi_flash: flash io: qio
W (88) spi_flash: Detected size(16384k) larger than the size in the binary image header(4096k). Using the size in the binary image header.
# Slot allocation: failed for 78848 bytesPRO CPU.
XS abort: memory full
```

**Comment by phoddie** [comment] 2023-04-14 14:34
This may just be an issue related to the fetch example. I'll look into that. We've run lots of tests with Wi-Fi on ESP-IDF 5. Did you try with any other examples, like $MODDABLE/examples/network/http/httpget?

Also, unrelated, but this note in your log is interesting:

> W (88) spi_flash: Detected size(16384k) larger than the size in the binary image header(4096k). Using the size in the binary image header.

Maybe we should add a custom partition map for the `m5stack_core2`. That would make all 16 MB available. The recent [automatic partitioning changes](https://github.com/Moddable-OpenSource/moddable/discussions/1087) will make that a bit easier too.

**Comment by stc1988** [comment] 2023-04-14 15:14
Thanks for response quickly.

I tried `examples/network/http/httpget` and it works.

**Comment by phoddie** [comment] 2023-04-14 15:36
Thanks for confirming that. I've updated the title and will try to look into this issue today.

**Comment by phoddie** [comment] 2023-04-14 21:27
This problem happens on the main branch too. 😱

The problem is a conflict between the new larger default memory allocations for ESP32 (and Pico) and the `creation` parameters in the manifest of the fetch application. A simple solution is to [delete the `creation` section](https://github.com/Moddable-OpenSource/moddable/blob/d77e86bc04601770c2ee531f98f2a7474c03efc4/examples/io/tcp/fetch/manifest.json#L5-L8) from the fetch application. That allows the fetch example to run normally again.

A general solution probably involves some work in `mcconfig` when merging manifest to avoid creating an impossible situation. I'll think about that.

**Comment by phoddie** [comment] 2023-05-17 16:52
This seems to be resolved. Can we close the issue?

**Closed as completed** 2023-05-17 22:32 UTC
