### ISSUE TITLE
 # Break: RegExp.prototype.flags: dead strip!  error, during esp32 build

### ISSUE THREAD

**Issue by Priyalakshmi-Laxmanan** [Moddable-OpenSource/moddable#203] opened 2019-05-27 10:11 UTC
Hi Team,

In reference to this issue https://github.com/Moddable-OpenSource/moddable/issues/196, I am trying to run the moddable after integrating with the third party scion.js file.

This is running perfectly in simulator mode (mcconfig -d -m -p win), but while tryinging to do a build for ESP32 setup, we are getting this error # Break: RegExp.prototype.flags: dead strip! 

In the documentation, we found the strip option in manifest file, is there any way to simply just exclude the functions for striping in the array instead of including all other needed functions.

If this has to be done in C source files, please let know what changes has to done for this

**Comment by phoddie** [comment] 2019-05-27 13:22
If `RegExp` is working in general (and I presume it is, as you did not report otherwise), but `flags` is failing, try referencing that explicitly in your project's main.js:

```
let foo = RegExp.prototype.flags;
```

If that does not resolve the problem, additional details will be required.

Note that in  `manifest_base.json` there is no different in how stripping is applied by platform. Is it possible you have overridden this with a "strip" option in your manifest?

**Comment by Priyalakshmi-Laxmanan** [comment] 2019-05-28 11:22
Hi Phoddie,

Thanks!
In our code we didn't used `flags` explicitly, the following is the code which caused 'dead strip' error,

```
var RX_WHITESPACE = /\s+/;
t.events = t.event.trim().split(RX_WHITESPACE);
```
Currently we have fixed this with a workaround,

`t.events = t.event.trim().replace(/  +/g, ' ').split(' ');`

No changes in the `manifest_base.json` is done, for the striping.

Also require one more information, 
Could you please tell us more information about flashing,  during flashing which path/binary file will be used for flashing into the device, to get more insight about build file sizes.

**Comment by phoddie** [comment] 2019-05-28 19:30
Thank you for the details. Now the problem is clear. We'll look at a solution. In the meanwhile, it looks like you have a workaround.

> Could you please tell us more information about flashing, during flashing which path/binary file will be used for flashing into the device, to get more insight about build file sizes

The flashing process uses the unmodified ESP IDF. The documentation from Espressif explains the details. The build tools report the binary image size when flashing. The binary is located at `$MODDABLE/build/bin/esp32/YOUR_BUILD_TARGET/debug/xs_esp32.bin`.

N.B. This is a distinct topic from the original issue. If you wish to discuss it further, please open a separate issue.

**Comment by Priyalakshmi-Laxmanan** [comment] 2019-05-29 12:03
Thanks for the response Phoddie!

We will wait for the your response regarding this issue.

For other topics, I will open a separate issue

**Comment by phoddie** [comment] 2019-08-05 12:43
Fix committed.

**Closed as completed by phoddie** 2019-08-05 12:43 UTC
