### ISSUE TITLE
`(<expression>,)` is incorrectly treated as valid

### ISSUE THREAD

**Issue by gibson042** [Moddable-OpenSource/moddable#726] opened 2021-10-26 18:31 UTC
**Environment:** XS 10.5.0

**Description**
XS seems to interpret a comma-terminated expression inside expression parentheses as valid, which it should not per [_CoverParenthesizedExpressionAndArrowParameterList_](https://tc39.es/ecma262/#prod-CoverParenthesizedExpressionAndArrowParameterList):
> <h2>Supplemental Syntax</h2>
> <p>When processing an instance of the production
>       <br>
>       <i>PrimaryExpression</i><sub><tt>[Yield, Await]</tt></sub> : <i>CoverParenthesizedExpressionAndArrowParameterList</i><sub><tt>[?Yield, ?Await]</tt></sub>
>       <br>
>       the interpretation of <i>CoverParenthesizedExpressionAndArrowParameterList</i> is refined using the following grammar:</p>
> <i>ParenthesizedExpression</i><sub><tt>[Yield, Await]</tt></sub> :
> <code>(</code> <i>Expression</i><sub><tt>[+In, ?Yield, ?Await]</tt></sub> <code>)</code>

**Steps to Reproduce**
```js
// In value position
void (Date,);
// In a left-hand side
(Date,) = null;
```

**Expected behavior**
Each of the above statements should produce a SyntaxError.

**Actual behavior**
Both statements are accepted as equivalent to their valid counterparts that don't have the trailing comma.

**Comment by phoddie** [comment] 2021-10-26 23:58
Hey @gibson042, thanks another detailed report. I'm able to duplicate your results. We'll take a look.

**Comment by phoddie** [comment] 2022-05-24 22:29
(The two commits referenced  above are mislabeled and do not apply to this report.)

**Comment by phoddie** [comment] 2022-05-31 22:33
FYI – the issue is related to parsing arrow functions, strangely enough. The expression is `(a, b, c, ) => {}` (also with trailing comma inside parenthesis) is allowed because it is an arrow function. The parser needs a little more state to detect the error. This is expected to be resolved in XS 13.

**Closed as completed** 2022-06-30 01:03 UTC
Labels: confirmed, fixed - please verify
