### ISSUE TITLE
"0" and "@" hash value conflicted?

### ISSUE THREAD

**Issue by linfan68** [Moddable-OpenSource/moddable#1209] opened 2023-09-12 11:00 UTC
It seems like if I put "@" into an JSON object, it's hash value got conflicted with "0"? Very interesting

from helloworld project:
```
debugger;

let message = "Hello, world - sample";
const chMap = {
  "0": 48,
  "@": 64,
}
trace(message + "\n\n");
trace('[0] of chMap is :' + chMap['0'].toString() + '\n\n');

trace(chMap['@'].toString() + '\n'); // This crashes
```

Expected output is :
```
Hello, world - sample

[0] of chMap is :48

64
```
But I got 
```
Hello, world - sample

[0] of chMap is :64

XS abort: unhandled exception
```

**Comment by phoddie** [comment] 2023-09-12 18:07
Very strange bug. Thanks for reporting it.

`chMap = {"@": 64}`  shows the problem most clearly. In that case, chMap contains `{"0":64}` which is obviously incorrect.

Doing `chMap = {}; chMap["@"] = 64` works as expected, setting chMap to `{"@":64}`.

That can co-exist with 0. `chMap = {"0": 48}; chMap["@"] = 64` results in `{"0":48,"@":64}`.

That suggests that the problem is in the parsing of `chMap = {"@": 64}` and not the runtime implementation of the object.

FWIW – you see "XS abort: unhandled exception" because `chMap['@']` evaluates to `undefined` and `undefined.toString()` throws an exception in JavaScript. If you write it as `String(chMap['@'])` it evaluates to `"undefined"`. That's just JavaScript trivia. ;)

We'll look into the bug

**Comment by phoddie** [comment] 2023-09-13 16:20
The test case works correctly in `xst`. So, it isn't parsing. It turns out the problem is in the linker. The fix is to change...

https://github.com/Moddable-OpenSource/moddable/blob/f50644664a298567e1b6a7ef018a88cca259661d/xs/tools/xslBase.c#L547

...to...

```c
		if (anID >= XS_SYMBOL_ID_COUNT)
			linker->symbolTable[aModulo] = aSymbol;
```

The problem would also occur with built-in symbols like `Symbol.asyncDispose`. Good find. Thanks again. Glad we got this fixed.

(The patch above will be merged to this repository in the coming days.)

**Comment by linfan68** [comment] 2023-09-18 05:17
> The test case works correctly in `xst`. So, it isn't parsing. It turns out the problem is in the linker. The fix is to change...
> 
> https://github.com/Moddable-OpenSource/moddable/blob/f50644664a298567e1b6a7ef018a88cca259661d/xs/tools/xslBase.c#L547
> 
> ...to...
> 
> ```c
> 		if (anID >= XS_SYMBOL_ID_COUNT)
> 			linker->symbolTable[aModulo] = aSymbol;
> ```
> 
> The problem would also occur with built-in symbols like `Symbol.asyncDispose`. Good find. Thanks again. Glad we got this fixed.
> 
> (The patch above will be merged to this repository in the coming days.)

I've verified with a local code change and it works. I'll close this issue, thanks!

**Comment by phoddie** [comment] 2023-09-18 16:25
Thank you for confirming. The fix is live in this repository now. We really appreciate your attention to detail in finding this issue.

**Comment by linfan68** [comment] 2023-11-18 16:28
@phoddie Can you verify this is fixed?
I just updated to latest public (4.3.0), the code looks like this:
```
		aSymbol->flag = flag;
		linker->symbolArray[anID] = aSymbol;
		if (table)
			linker->symbolTable[aModulo] = aSymbol;
		linker->symbolIndex++;
```

And the problem found in my code still exists.
After changing to:

```
		aSymbol->flag = flag;
		linker->symbolArray[anID] = aSymbol;
		if (table)
			if (anID >= XS_SYMBOL_ID_COUNT)
				linker->symbolTable[aModulo] = aSymbol;
		linker->symbolIndex++;
```

It got fixed.

**Comment by phoddie** [comment] 2023-11-19 02:03
It looks like one fix stepped on another. Sorry about that. Your merge of the two fixes does seem to work. We'll review that and update.

**Comment by phoddie** [comment] 2023-11-19 23:58
Just FYI – merging the two changes works on a clean build, but can fail on an incremental build. We have a fix that should always work. That will be live soon.

Thanks for reporting this issue, again.

**Comment by phoddie** [comment] 2023-11-24 19:38
This should be better now. Please try with the latest. Thank you,

**Comment by phoddie** [comment] 2023-12-23 01:38
Closing (fixed).

**Closed as completed by phoddie** 2023-12-23 01:38 UTC
Labels: fixed - please verify
