### ISSUE TITLE
Cannot coerce symbol (from 5th property on BigInt64Array) to string

### ISSUE THREAD

**Issue by dckc** [Moddable-OpenSource/moddable#480] opened 2020-10-21 02:18 UTC
```js
const monster = Reflect.ownKeys(BigInt64Array);
const sonOfMonster = Object(monster[4]);

// these don't throw.
String(Symbol('hello'));
String(Symbol());

String(sonOfMonster);
// TypeError: String: Cannot coerce symbol to string
```

**Build environment:** Linux
**Target device:** xsnap

cc @warner @erights @kriskowal @phoddie

**Comment by phoddie** [comment] 2020-10-21 16:44
duplicate of #479

**Closed as completed by phoddie** 2020-10-21 16:44 UTC
Labels: duplicate, confirmed
