### ISSUE TITLE
Write + read error in am2320

### ISSUE THREAD

**Issue by louisvangeldrop** [Moddable-OpenSource/moddable#1311] opened 2024-02-22 12:20 UTC
**Target device:** NodeMCU ESP32c3-devkit

**Description**
I'am using the example from folder  %MODDABLE%\examples\drivers\sensors\am2320

**Steps to Reproduce**
1. Build and install the app using this build command: `mcconfig -m -d -p esp32/c3_32s_kit`
2. I get a Write error at line 88:io.write(cBuf) in debug window: 
``` 
                Timer.delay(10);
		
		// start conversion
		cBuf[0] = Register.COMMAND_READ;
		cBuf[1] = reg;
		cBuf[2] = 0x02;
         	io.write(cBuf);
		Timer.delay(2);

```

I have looked at the Adafruit am2320 driver: https://github.com/adafruit/Adafruit_AM2320/blob/master/Adafruit_AM2320.cpp
and changed the delay-duration in Timer.delay(10+100). As a result I don't get the write error.

However I also have to change the Timer.delay(2) into Timer.delay(2+5) to avoid an io.read error.

**Comment by louisvangeldrop** [comment] 2024-02-22 14:05
I have changed the "wake" code just like the Adafruit-code into:
```
               for (let i = 0; i < 3; i++) {
			try {
				io.write(new ArrayBuffer(8));	// write 8 length buffer
				written = true
				break
			}
			catch (e) {
				Timer.delay(100)
			}
		}
```

That works.

**Comment by phoddie** [comment] 2024-02-22 19:55
I guess @mkellner didn't encounter the read/write failures that you are experiencing when he wrote the original driver.

100 ms is a looong time to wait. I quickly checked the data sheet and it seemed to indicate a shorter time should be enough. Does it fail with shorter times (like 10ms)?

Would you like to make a PR to merge this change?

**Comment by louisvangeldrop** [comment] 2024-02-22 21:50
I have changed 100 ms in 10 ms and it works.

**Comment by louisvangeldrop** [comment] 2024-02-22 22:08
BTW I have no idea how make a PR. Maybe I am too old for it.

**Comment by phoddie** [comment] 2024-02-22 23:29
No problem. I've merged your changes. They were incomplete (how `written` is handled is omitted from the snippet above), so I made a guess. I also did some cleanup on the driver, since it used some older coding patterns.

The full source is on [this gist](https://gist.github.com/phoddie/aa72867fbd8c295ecc4840a70a6a4c86). Could you give that a try? I confirmed it compiles but I don't have the sensor to confirm it actually works. Once you confirm that, I'll commit it. Thanks!

**Comment by louisvangeldrop** [comment] 2024-02-23 20:41
Tests running last night and today showed that the 10 ms delay is too short. Sometimes the temperature or humidity value is undefined. With a 100ms delay I do get twice a "catched" exception and with 50 ms three times. Both delays produce correct temperature and humidity values.

**Comment by phoddie** [comment] 2024-02-23 21:30
Thanks for giving it a try. The timing / retry behavior seems like a mysterious incantation. Since I don't really understand it, it seems safest to duplicate the Adafruit approach. I've updated [the gist](https://gist.github.com/phoddie/aa72867fbd8c295ecc4840a70a6a4c86) to do that. Does that work for you?

**Comment by louisvangeldrop** [comment] 2024-02-24 18:51
It works. Thx for the help

**Comment by phoddie** [comment] 2024-02-24 23:13
Cool, thanks. Will get that committed.

FWIW – the delays are long enough to be a bit annoying. They exist because the sensor automatically powers down to save power if the sampling interval is high enough. An alternative would be to use a repeating timer to keep the sensor active. There could be an option to disable that, but at least the default behavior would be more-or-less non-blocking.

**Closed as completed by phoddie** 2024-02-24 23:13 UTC
