### ISSUE TITLE
How to run 'mcrun' command

### ISSUE THREAD

**Issue by LongNguyen1984** [Moddable-OpenSource/moddable#466] opened 2020-09-27 06:52 UTC
Do you have questions about

I try to run the example for helloworld from 'mcrun -d -m -p esp32'
but it return to:
### TypeError: cannot coerce undefined to object

How to fix it?

**Comment by phoddie** [comment] 2020-09-28 04:46
(Closing as duplicate of an [issue](https://github.com/Moddable-OpenSource/iot-product-dev-book/issues/2) in another repository.)

**Closed as completed by phoddie** 2020-09-28 04:46 UTC
